### PR TITLE
Update to version 2017.1.0

### PR DESCRIPTION
**Pull request by johannesring**

### CODE REVIEW

**Comment by johannesring** [comment]
Now it fails to `import mshr` during the tests with the following message:
``` console
DOLFIN runtime dependency is not met.
Install the following python module: 'ufl' 
and make sure its location is listed in PYTHONPATH.
```
`ufl` is part of `fenics`. Should `fenics` be added to `requires` for tests?

**Comment by johannesring** [comment]
It didn't work adding `fenics` to `requires` for tests. Does anyone have an idea why it fails to find `ufl`? @minrk?

**Comment by ericnchen** [comment]
@johannesring I forked the original and removed the two patches as you did and updated mshr to use the 2017.1.0 archives and it seems to work perfectly fine for me. See https://github.com/sudoeric/mshr-feedstock/commit/5fd4931e00533dc0918fcfdb979002a07a3fbfc0. The only change I made was adding HDF5 as a requirement and I'm using Python 3.6.1 as provided by Anaconda.

**Comment by minrk** [comment]
The failure is due to fenics 2017.1 depending on setuptools but not expressing that dependency in the conda package. Local builds won't demonstrate the failure because conda's default behavior is to artificially add setuptools as a dependency of the `python` package, whereas conda-forge's CI builds [disable this](https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/235b16f2b9801b14a7d6cc65ac7989aac736fbb2/recipe/run_conda_forge_build_setup_linux#L10). Re-triggering these builds should succeed as soon as fenics-2017.1.0-1 finishes uploading, in an hour or two.

**Comment by minrk** [comment]
Success!

**Pull request merged**
